import { supabase } from './supabase.js';
import { loadSession, resolveTenantIdFromSession, requireActiveSubscription } from './context.js';
import type { ServiceOrderCreateRequestDto, ServiceOrderDto } from '@sdmx/contracts';
import { randomUUID } from 'node:crypto';

export class LegacyMigrationService {
  /**
   * Migrates logic from Service_crearSolicitud (legacy-srfix/gs/Services.gs).
   * Creates a new service order request in the new multi-tenant Supabase backend.
   */
  async createLegacyServiceRequest(token: string, data: any): Promise<ServiceOrderDto> {
    const session = await loadSession(token);
    requireActiveSubscription(session);
    const tenantId = resolveTenantIdFromSession(session);

    // Placeholder for legacy validation logic (Service_validarPayloadCrearSolicitud)
    // For now, we'll map fields directly, assuming frontend will send validated data
    // or we'll add a more robust validation layer here.
    const payload: ServiceOrderCreateRequestDto = {
      tenantId: tenantId,
      customerId: data.customerId ?? null, // New field, assuming it's passed or derived
      deviceType: data.dispositivo ?? data.deviceType ?? null,
      deviceBrand: data.marca ?? data.deviceBrand ?? null,
      deviceModel: data.modelo ?? data.deviceModel ?? null,
      reportedIssue: data.problemas ?? data.descripcion ?? data.reportedIssue ?? null,
      estimatedCost: data.cotizacionTotal ?? data.estimatedCost ?? null,
      notes: data.notas ?? data.notes ?? null,
      promisedDate: data.fechaEntrega ?? data.promisedDate ?? null,
      serialNumber: data.serial ?? data.serialNumber ?? null,
      accessories: data.accesorios ?? data.accessories ?? null,
      internalNotes: data.notasInternas ?? data.internalNotes ?? null,
      warrantyUntil: data.garantiaHasta ?? data.warrantyUntil ?? null,
      evidenceMetadata: data.evidenciaMetadata ?? data.evidenceMetadata ?? [],
      // Map legacy status if available, otherwise default to 'received' or 'pending'
      status: data.estado ?? 'pending',
      // The folio will be auto-generated by the DB (SERIAL) if not provided.
      // If a specific folio is intended, it should be passed here, but for 'crearSolicitud'
      // it was usually generated. Supabase `SERIAL` handles this.
    };

    // Note: The legacy Service_crearSolicitud uses `obtenerSiguienteFolio` for 'COT-' prefix.
    // In the new system, `folio` is `SERIAL` (auto-incrementing bigint).
    // If a custom folio generation is needed, it should be done BEFORE insert and passed in `payload.folio`.
    // For now, we rely on `SERIAL` in Supabase.

    const created = await supabase.insert<ServiceOrderDto[]>('service_orders', token, payload);
    if (!created || created.length === 0) {
      throw new Error('Failed to create service order request');
    }
    return created[0];
  }
}

export const legacyMigrationService = new LegacyMigrationService();
